# Generated by Django 5.2.9 on 2025-12-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='repeat_interval',
        ),
        migrations.AddField(
            model_name='reminder',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='once', max_length=50),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
